# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rawq}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Craig Jackson"]
  s.date = %q{2011-10-26}
  s.default_executable = %q{rawq}
  s.description = %q{Ruby media streaming web application

Simply install and run on a server. Access the web application with any well-supported HTML5 browser.
}
  s.email = %q{tapocol@gmail.com}
  s.executables = ["rawq"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/rawq",
    "lib/rawq.rb",
    "lib/rawq/generator.rb",
    "lib/rawq/generator/application.rb",
    "lib/rawq/generator/options.rb",
    "lib/rawq/templates/Gemfile",
    "lib/rawq/templates/application.rb",
    "lib/rawq/templates/lib/config.rb.erb",
    "lib/rawq/templates/public/favicon.ico",
    "lib/rawq/templates/public/index.html.erb",
    "lib/rawq/templates/public/javascript/audio_player.js",
    "lib/rawq/templates/public/javascript/ejs/ejs_production.js",
    "lib/rawq/templates/public/javascript/jquery/jquery.min.js",
    "lib/rawq/templates/public/javascript/local_storage.js",
    "lib/rawq/templates/public/javascript/music_list.js",
    "lib/rawq/templates/public/javascript/rawq.js",
    "lib/rawq/templates/public/javascript/view.js",
    "lib/rawq/templates/public/templates/audio_sources.ejs",
    "lib/rawq/templates/public/templates/music_list_item.ejs",
    "lib/rawq/version.rb",
    "rawq.gemspec",
    "test/helper.rb",
    "test/rawq/generator/test_application.rb",
    "test/rawq/generator/test_options.rb",
    "test/rawq/test_generator.rb"
  ]
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby web app for media management/streaming through HTTP with HTML5 interface}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

